---
- hosts: webservers
  become: yes
  tasks:
    - yum:
        name: "{{item}}"
        state: latest
      loop:
        - httpd
        - ufw
        - php
        - git

    - service:
        name: "{{item}}"
        state: started
        enabled: yes
      loop:
        - httpd
        - ufw
    
    - name: Allow all access to tcp ports
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
    
    - name: Example clone of a single branch
      git:
        repo: https://github.com/L00170299/ScriptingTheDeployPipeline.git
        dest: /tmp/deploy
        single_branch: yes
        version: master

- hosts: sqlservers
  become: yes
  tasks:
    - yum:
        name: "{{item}}"
        state: latest
      loop:
        - community-mysql-server
        - python3-mysql
        - ufw
        - php
        - git

    - service:
        name: "{{item}}"
        state: started
        enabled: yes
      loop:
        - mysqld
        - ufw

    - name: creating mysql user (lyit_user)
      mysql_user:
        name: "lyit_user"
        password: "lyit_pass"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: creating lyit_db
      mysql_db:
        name: "lyit_db"
        state: present
    
    - name: Allow all access to tcp ports
      community.general.ufw:
        rule: allow
        port: '3306'
        proto: tcp

    - name: Clone of a single branch
      git:
        repo: https://github.com/L00170299/ScriptingTheDeployPipeline.git
        dest: /tmp/deploy
        single_branch: yes
        version: master

    - name: insert sample data into database
      mysql_db:
        name: lyit_db
        state: import
        target: /tmp/deploy/Ansible/website/table.sql
        login_user: lyit_user
        login_password: lyit_pass