---
- hosts: webservers
  become: yes
  vars:
    git_repo: "https://github.com/L00170299/ScriptingTheDeployPipeline.git"
    sql_user: "lyit_user"
    sql_pass: "lyit_pass"
    sql_db: "lyit_db"

  tasks:
    - yum:
        name: "{{item}}"
        state: latest
      loop:
        - httpd
        - ufw
        - php
        - php-mysqlnd
        - git

    - service:
        name: "{{item}}"
        state: started
        enabled: yes
      loop:
        - httpd
        - ufw
    
    - name: Allow all access to tcp ports
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
    
    - name: Clone of a single branch
      git:
        repo: "{{git_repo}}"
        dest: /tmp/deploy

    - name: Deploy php page
      ansible.builtin.copy:
        src: /tmp/deploy/Ansible/website/index.php
        dest: /var/www/html/
        remote_src: yes

- hosts: sqlservers
  become: yes
  vars:
    git_repo: "https://github.com/L00170299/ScriptingTheDeployPipeline.git"
    sql_user: "lyit_user"
    sql_pass: "lyit_pass"
    sql_db: "lyit_db"
  tasks:
    - yum:
        name: "{{item}}"
        state: latest
      loop:
        - community-mysql-server
        - python3-mysql
        - ufw
        - php
        - git
        - awscli
        - python3-boto3
        - python3-botocore

    - service:
        name: "{{item}}"
        state: started
        enabled: yes
      loop:
        - mysqld
        - ufw

    - name: creating mysql user
      mysql_user:
        name: "{{sql_user}}"
        password: "{{sql_pass}}"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: creating database
      mysql_db:
        name: "{{sql_db}}"
        state: present
    
    - name: Allow all access to tcp ports
      community.general.ufw:
        rule: allow
        port: '3306'
        proto: tcp

    - name: Clone of a single branch
      git:
        repo: "{{git_repo}}"
        dest: /tmp/deploy

    - name: insert sample data into database
      mysql_db:
        name: "{{sql_db}}"
        state: import
        target: /tmp/deploy/Ansible/website/table.sql
        login_user: "{{sql_user}}"
        login_password: "{{sql_pass}}"